name: SISU Programs
favicon: null
layout_spectrum: 0.044995567528530955
typography_spectrum: 0.003565113991498947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9785006032325327
  lightness: 0.13817777880467474
  saturation: 0.022820388665422797
  rhythmicContrast: 0.8801997487898916
purpose: []
